import streamlit as st
import pandas as pd
import numpy as np
import pickle
import os

# ── Google Drive File IDs ─────────────────────────────────────────────────────
# CSVs (raw data)
# Artifacts (pre-trained — generated by save_artifacts.py)
DRIVE_IDS = {
    "orders.csv":                "1beOjK3v7hFLbYvapshc8eDHg8-_1Tlh9",
    "products.csv":              "1yTib9V_yh-v9MSvGviW_TNuxLHLFOKN0",
    "order_products__prior.csv": "1nsvu044dz4S6cjQ3n28xsPbHS_IPcAE4",
    "order_products__train.csv": "16sTwt7_rZkhnYQdZCcFvdE6T0hoBjOhz",

    # ↓ paste the Drive IDs for these after running save_artifacts.py
    "model.pkl":                 "1R3rGn0DL_1BQgFe791vWmyXNpd1vPakk",
    "apriori_rules.pkl":         "157iZajxTTOaOYyAR-sjPLqIBwX_xkYmz",
}

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR  = os.path.join(BASE_DIR, "data")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _local_path(name):
    for p in [os.path.join(DATA_DIR, name), os.path.join(BASE_DIR, name), name]:
        if os.path.exists(p):
            return p
    return None


def _download(name):
    try:
        import gdown
    except ImportError:
        st.error("gdown not installed. Add gdown to requirements.txt.")
        st.stop()

    os.makedirs(DATA_DIR, exist_ok=True)
    dest = os.path.join(DATA_DIR, name)
    fid  = DRIVE_IDS[name]

    if fid.startswith("PASTE_"):
        st.error(
            f"No Drive ID set for `{name}`. "
            "Run save_artifacts.py locally, upload the file to Drive, and paste the ID into DRIVE_IDS."
        )
        st.stop()

    with st.spinner(f"Downloading {name} from Google Drive… (once only)"):
        gdown.download(
            f"https://drive.google.com/uc?id={fid}",
            dest, quiet=False
        )

    if not os.path.exists(dest):
        st.error(f"Download failed for {name}. Check Drive sharing is 'Anyone with the link'.")
        st.stop()

    return dest


def _get(name):
    path = _local_path(name)
    if path:
        return path
    if name in DRIVE_IDS:
        return _download(name)
    st.error(f"'{name}' not found and no Drive ID configured.")
    st.stop()


# ── Optimised CSV readers ─────────────────────────────────────────────────────

def _read_orders(path):
    df = pd.read_csv(
        path,
        usecols=["order_id", "user_id", "eval_set", "order_number",
                 "order_dow", "order_hour_of_day", "days_since_prior_order"],
        dtype={"order_id": "int32", "user_id": "int32", "eval_set": "category",
               "order_number": "int16", "order_dow": "int8", "order_hour_of_day": "int8"}
    )
    df["days_since_prior_order"] = pd.to_numeric(
        df["days_since_prior_order"], errors="coerce").astype("float32")
    return df


def _read_products(path):
    return pd.read_csv(
        path,
        usecols=["product_id", "product_name"],
        dtype={"product_id": "int32", "product_name": "str"}
    )


def _read_order_products(path):
    return pd.read_csv(
        path,
        usecols=["order_id", "product_id", "add_to_cart_order", "reordered"],
        dtype={"order_id": "int32", "product_id": "int32",
               "add_to_cart_order": "int8", "reordered": "int8"}
    )


# ── Public loaders ────────────────────────────────────────────────────────────

@st.cache_data(show_spinner="Loading datasets…")
def load_raw():
    try:
        orders         = _read_orders(_get("orders.csv"))
        products       = _read_products(_get("products.csv"))
        order_products = _read_order_products(_get("order_products__prior.csv"))
        train          = _read_order_products(_get("order_products__train.csv"))
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return None, [str(e)]

    return dict(orders=orders, products=products,
                order_products=order_products, train=train), []


@st.cache_data(show_spinner="Building combined dataset…")
def load_combined():
    raw, missing = load_raw()
    if raw is None:
        return None

    df = (
        raw["order_products"]
        .merge(
            raw["orders"][["order_id", "user_id", "order_number", "order_dow",
                           "order_hour_of_day", "days_since_prior_order"]],
            on="order_id", how="left"
        )
        .merge(
            raw["products"][["product_id", "product_name"]],
            on="product_id", how="left"
        )
    )

    days_map = {0:"Sun", 1:"Mon", 2:"Tue", 3:"Wed", 4:"Thu", 5:"Fri", 6:"Sat"}
    df["day_name"]     = df["order_dow"].map(days_map).astype("category")
    df["product_name"] = df["product_name"].astype("category")
    return df


@st.cache_data(show_spinner="Engineering features…")
def load_features():
    df = load_combined()
    if df is None:
        return None, None, None

    user_features = (
        df.groupby("user_id").agg(
            order_number=("order_number", "max"),
            days_since_prior_order=("days_since_prior_order", "mean"),
            order_hour_of_day=("order_hour_of_day", "mean"),
            order_dow=("order_dow", "mean"),
        ).round(2).rename(columns={
            "order_number":           "total_orders",
            "days_since_prior_order": "avg_days_between_orders",
            "order_hour_of_day":      "preferred_hour",
            "order_dow":              "preferred_day",
        })
    )

    product_features = (
        df.groupby("product_id").agg(
            reordered=("reordered", "mean"),
            order_hour_of_day=("order_hour_of_day", "mean"),
            order_dow=("order_dow", "mean"),
        ).round(3).rename(columns={
            "reordered":         "product_reorder_rate",
            "order_hour_of_day": "product_avg_hour",
            "order_dow":         "product_avg_dow",
        })
    )

    up = (
        df.groupby(["user_id", "product_id"]).agg(
            order_id=("order_id", "count"),
            reordered_sum=("reordered", "sum"),
            reordered_mean=("reordered", "mean"),
            add_to_cart_order=("add_to_cart_order", "mean"),
            days_since_prior_order=("days_since_prior_order", "mean"),
        ).round(3).rename(columns={
            "order_id":               "up_order_count",
            "reordered_sum":          "up_reorder_count",
            "reordered_mean":         "up_reorder_rate",
            "add_to_cart_order":      "up_avg_cart_pos",
            "days_since_prior_order": "up_avg_days_between",
        })
    )

    return user_features, product_features, up


@st.cache_data(show_spinner="Loading association rules…")
def load_apriori_rules():
    """
    Loads pre-computed Apriori rules from pickle (generated by save_artifacts.py).
    Falls back to computing on-the-fly if pkl not available.
    """
    path = _get("apriori_rules.pkl")
    try:
        with open(path, "rb") as f:
            rules = pickle.load(f)
        return rules
    except Exception:
        pass

    # Fallback: compute live (slower, more RAM)
    df = load_combined()
    if df is None:
        return None
    try:
        from mlxtend.frequent_patterns import apriori, association_rules
        import warnings; warnings.filterwarnings("ignore")

        top_products  = df["product_name"].value_counts().head(100).index
        filtered      = df[df["product_name"].isin(top_products)]
        sample_orders = filtered["order_id"].drop_duplicates().head(3000)
        filtered      = filtered[filtered["order_id"].isin(sample_orders)]

        basket = (
            filtered
            .groupby(["order_id", "product_name"])["product_name"]
            .count().unstack().reset_index()
            .fillna(0).set_index("order_id")
            .astype(bool)
        )

        freq_items = apriori(basket, min_support=0.01, use_colnames=True)
        rules = association_rules(freq_items, metric="lift", min_threshold=1.0)
        rules["antecedents"] = rules["antecedents"].apply(lambda x: ", ".join(sorted(x)))
        rules["consequents"] = rules["consequents"].apply(lambda x: ", ".join(sorted(x)))
        rules = rules[["antecedents", "consequents", "support",
                        "confidence", "lift", "leverage", "conviction"]]
        return rules.sort_values("lift", ascending=False).reset_index(drop=True)
    except Exception:
        return None


FEATURE_COLS = [
    "up_order_count", "up_reorder_count", "up_reorder_rate",
    "up_avg_cart_pos", "up_avg_days_between",
    "total_orders", "avg_days_between_orders", "preferred_day", "preferred_hour",
    "product_reorder_rate", "product_avg_hour", "product_avg_dow",
]


@st.cache_resource(show_spinner="Loading model…")
def load_model():
    """
    Loads pre-trained model from pickle (generated by save_artifacts.py).
    Falls back to training on-the-fly if pkl not available.
    """
    path = _get("model.pkl")
    try:
        with open(path, "rb") as f:
            artifact = pickle.load(f)
        return (
            artifact["model"],
            artifact["metrics"],
            artifact["feat_imp"],
            artifact["threshold"],
            artifact["feature_cols"],
        )
    except Exception:
        pass

    # Fallback: train live (slow, high RAM)
    raw, _ = load_raw()
    if raw is None:
        return None, None, None, None, None

    user_features, product_features, up = load_features()
    if user_features is None:
        return None, None, None, None, None

    orders   = raw["orders"]
    train_df = raw["train"]

    try:
        import xgboost as xgb
        from sklearn.metrics import (f1_score, roc_curve, auc, confusion_matrix,
                                     precision_score, recall_score, accuracy_score)

        np.random.seed(42)
        uniq_train_users = orders.query("eval_set == 'train'")["user_id"].unique()
        sample_size  = min(int(0.5 * len(uniq_train_users)), 20000)
        sampled      = np.random.choice(uniq_train_users, size=sample_size, replace=False)
        train_users  = sampled[:int(0.7 * len(sampled))]
        test_users   = sampled[int(0.7 * len(sampled)):]

        def make_dataset(user_list):
            base = (
                up.reset_index()
                .query("user_id in @user_list")
                .merge(user_features,    on="user_id",    how="left")
                .merge(product_features, on="product_id", how="left")
            )
            last = (
                orders.query("user_id in @user_list and eval_set == 'train'")
                .merge(train_df, on="order_id")[["user_id", "product_id"]]
                .assign(target=1)
            )
            return (
                base.merge(last, on=["user_id", "product_id"], how="left")
                .fillna({"target": 0})
                .query("up_order_count >= 2")
            )

        train_data = make_dataset(train_users)
        test_data  = make_dataset(test_users)

        X_train = train_data[FEATURE_COLS].fillna(0)
        y_train = train_data["target"]
        X_test  = test_data[FEATURE_COLS].fillna(0)
        y_test  = test_data["target"]

        scale_pos = (y_train == 0).sum() / (y_train == 1).sum()

        model = xgb.XGBClassifier(
            objective="binary:logistic", eval_metric="auc",
            random_state=42, n_estimators=200, learning_rate=0.05,
            max_depth=5, subsample=0.8, colsample_bytree=0.8,
            scale_pos_weight=scale_pos, use_label_encoder=False,
            tree_method="hist",
        )
        model.fit(X_train, y_train)

        train_prob = model.predict_proba(X_train)[:, 1]
        test_prob  = model.predict_proba(X_test)[:, 1]

        best_f1, best_threshold = 0, 0.5
        for thr in np.arange(0.1, 0.9, 0.02):
            preds = (train_prob >= thr).astype(int)
            f = f1_score(y_train, preds)
            if f > best_f1:
                best_f1, best_threshold = f, thr

        test_pred   = (test_prob >= best_threshold).astype(int)
        fpr, tpr, _ = roc_curve(y_test, test_prob)
        roc_auc     = auc(fpr, tpr)

        metrics = {
            "accuracy":  accuracy_score(y_test, test_pred),
            "precision": precision_score(y_test, test_pred),
            "recall":    recall_score(y_test, test_pred),
            "f1":        f1_score(y_test, test_pred),
            "roc_auc":   roc_auc,
            "threshold": best_threshold,
            "fpr": fpr, "tpr": tpr,
            "cm": confusion_matrix(y_test, test_pred),
            "train_f1": f1_score(y_train, (train_prob >= best_threshold).astype(int)),
        }

        feat_imp = pd.DataFrame({
            "feature":    FEATURE_COLS,
            "importance": model.feature_importances_,
        }).sort_values("importance", ascending=False)

        return model, metrics, feat_imp, best_threshold, X_train.columns.tolist()

    except Exception as e:
        st.error(f"Model training failed: {e}")
        return None, None, None, None, None
